#!/usr/bin/env python
import os

import requests


github_repos = [
    {'name': 'custom_bootstrap_build_with_scss', 'published_date': '2016-07-25'},
    {'name': 'mocha_setup', 'published_date': '2016-08-02'},
    {'name': 'webpack_example', 'published_date': '2016-09-27'},
]



def create_post(title, published_date, body_md):
    metadata_template = \
u'''---
layout: post
title: "{title}"
date: {published_date}
---
{body_md}
'''
    post_md_without_title = '\n'.join([line for line in body_md.split('\n')[1:]])
    return metadata_template.format(
        title=title,
        published_date=published_date,
        body_md=post_md_without_title
    )


def get_readme_url(repo_name):
    return 'http://raw.githubusercontent.com/tdpreece/{}/master/README.md'.format(repo_name)


def save_post(name, published_date, post_md):
    kebab_case_name = name.replace('_', '-')
    file_name = '{}-{}.md'.format(published_date, kebab_case_name)
    this_dir = os.path.dirname(os.path.realpath(__file__))
    posts_dir = os.path.join(
        os.path.dirname(this_dir),
        '_posts'
    )
    file_path = os.path.join(posts_dir, file_name)
    with open(file_path, 'w') as fp:
        fp.write(post_md.encode('utf8'))


def main():
    for repo in github_repos:
        readme_url = get_readme_url(repo['name'])
        response = requests.get(readme_url)
        readme_md = response.text
        title = readme_md.split('\n')[0][1:].strip()
        post_md = create_post(title, repo['published_date'], readme_md)
        save_post(repo['name'], repo['published_date'], post_md)



if __name__ == '__main__':
    main()
